### ISSUE TITLE
爬取12条后 403 error

### ISSUE THREAD

**Issue by Juntaran** [linqingmaoer/Instagram_crawler#1]
请求网页json错误, 错误状态码： 403
Traceback (most recent call last):
  File "/Users/juntaran/Workspace/pyWorkspace/instagramSpider/ins.py", line 136, in <module>
    main("sakumomo1203")
  File "/Users/juntaran/Workspace/pyWorkspace/instagramSpider/ins.py", line 113, in main
    urls = get_urls(html)
  File "/Users/juntaran/Workspace/pyWorkspace/instagramSpider/ins.py", line 91, in get_urls
    infos = js_data['data']['user']['edge_owner_to_timeline_media']['edges']
TypeError: 'NoneType' object is not subscriptable

**Comment by ginping** [comment]
有没有在headers里加上自己的cookie呐

**Comment by Juntaran** [comment]
> 有没有在headers里加上自己的cookie呐

soga 好像没加，我有空试下
